#!/bin/bash

Utility="\e[31m$0\e[0m"
B="\e[1m"
N="\e[0m"

Usage() {
    echo -e "
$Utility manages the kubernetes cluster for making ease of lab setup for Kubernetes trainings

Following are the CLuster Actions:
  $Utility ${B}create${N}   <Cluster-Name>          -> To create the cluster with default options.
  $Utility ${B}list${N}                             -> To list the clusters availble in your google account.
  $Utility ${B}destroy${N}  <Cluster-Name>          -> To delete the cluster with default options.
  $Utility ${B}backup${N}   <Cluster-Name>          -> To take the backup of complete cluster (In Development, may not work as expected)
  $Utility ${B}scaleup${N}    <no-of-nodes>         -> Scales up to the desired number of nodes given. (Max of 5)
  $Utility ${B}scaledown${N}  <no-of-nodes>         -> Scales down to the desired number of nodes given. (Min of 1)

    "
    exit 1
}

Run() {
    echo -e "\nRunning the following command\n\n\t\e[1m$@\e[0m\n"
}


if [ "$1" = "help" -o -z "$1" ]; then 
    Usage
fi 
ACTION=$1
ACTION=$(echo $ACTION | tr [A-Z] [a-z])

gcloud compute instances list &>/dev/null 
if [ $? -ne 0 ]; then 
    echo -e "\e[1;31mFailed to connect to google cloud\e[0m\n\n\tYou can use the following URL and setup google cloud access on this server\n\t\tSOME-URL"
    exit 2
fi

case $ACTION in 
    list) 
        Run "gcloud container clusters list"
        COUNT=$(gcloud container clusters list| wc -l ) 
        if [ $COUNT -eq 0 ]; then 
            echo "There are no clusters in this project"
            exit 0 
        fi 
    ;;
esac
