#!/bin/bash

Utility="\e[31m$0\e[0m"
B="\e[1m"
N="\e[0m"
ZONE=us-east1-b

Usage() {
    echo -e "
$Utility manages the kubernetes cluster for making ease of lab setup for Kubernetes trainings

Following are the Cluster Actions:
  $Utility ${B}create${N}       <Cluster-Name>                -> To create the cluster with default options.
  $Utility ${B}list${N}                                       -> To list the clusters availble in your google account.
  $Utility ${B}destroy${N}      <Cluster-Name>                -> To delete the cluster with default options.
  $Utility ${B}backup${N}       <Cluster-Name>                -> To take the backup of complete cluster. ${B}(In Development, may not work as expected)${N}
  $Utility ${B}scaleup${N}      <Cluster-Name> <no-of-nodes>  -> Scales up to the desired number of nodes given. (Max of 5)
  $Utility ${B}scaledown${N}    <Cluster-Name> <no-of-nodes>  -> Scales down to the desired number of nodes given. (Min of 1)
  $Utility ${B}setup-config${N} <Cluster-Name>                -> Update the kube-config for the cluster.

  \e[1;4;33;41mNote:\e[0m Cluster Names should be in small characters and numbers with out any special characters other than '-'
    "
    exit 1
}

Run() {
    echo -e "\nRunning the following command\n\n\t\e[1m$ $@\e[0m\n"
}

Check_Cluster_Exists() {
    Cluster_Name=$1
    gcloud container clusters list| grep $Cluster_Name &>/dev/null 
    if [ $? -eq 0 ]; then 
        return 1
    else
        return 2
    fi 
}


if [ "$1" = "help" -o -z "$1" ]; then 
    Usage
fi 
ACTION=$1
ACTION=$(echo $ACTION | tr [A-Z] [a-z])

gcloud compute instances list &>/dev/null 
if [ $? -ne 0 ]; then 
    echo -e "\e[1;31mFailed to connect to google cloud\e[0m\n\n\tYou can use the following URL and setup google cloud access on this server\n\t\tSOME-URL"
    exit 2
fi

case $ACTION in 
    list) 
        Run "gcloud container clusters list"
        COUNT=$(gcloud container clusters list| wc -l ) 
        if [ $COUNT -eq 0 ]; then 
            echo "There are no clusters in this project"
            exit 0 
        fi 
    ;;
    create) 
        Cluster_Name=$2
        if [ -z "$Cluster_Name" ]; then 
            echo -e "\n\e[1;31m*** Argument Missing ***\e[0m"
            Usage 
        fi
        echo -e "Creating Cluster"
        Check_Cluster_Exists $Cluster_Name
        [ $? -eq 1 ] && echo -e "\t*** Cluster Already exists ***" && exit 0
        Run "gcloud container clusters create $Cluster_Name --zone $ZONE"
        gcloud container clusters create $Cluster_Name --zone $ZONE 2>/dev/null
        echo -e "\n"
        echo -e "Updating Kubectl config"
        
    ;;
    delete)
        Cluster_Name=$2
        if [ -z "$Cluster_Name" ]; then 
            echo -e "\n\e[1;31m*** Argument Missing ***\e[0m"
            Usage 
        fi
        echo -e "Creating Cluster"
        Check_Cluster_Exists $Cluster_Name
        [ $? -eq 2 ] && echo -e "\t*** Cluster does not exists ***" && exit 0
        Run "gcloud container clusters delete $Cluster_Name --zone $ZONE"
        gcloud container clusters delete $Cluster_Name --zone $ZONE
        echo -e "\n\n"
    ;;
    backup|scale*) echo "Still in Progress" ;;

    *) Usage ;;
esac
